# Generated by Django 4.1 on 2022-08-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todouser',
            old_name='username',
            new_name='user_id',
        ),
    ]
