# Generated by Django 4.1 on 2022-08-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_username_todouser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todouser',
            name='id',
        ),
        migrations.AlterField(
            model_name='todouser',
            name='user_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
